

POST http://localhost:8000/userLogin/login 
content-type: application/json

{
    "email": "ishan@gmail.com",
    "password": "ishan"
}

###

POST http://localhost:8000/userLogin/signup 
content-type: application/json

{
    "name": "ishan",
    "email": "ishan@gmail.com",
    "password": "ishan"
    
}

###

POST http://localhost:8000/employeeFunctions/addNewFlight 
content-type: application/json

{
    "flightName": "UTD2",
    "departure":{
                    "airport": "BOM1",
                    "time":,
                    "city": "Mumbai"
                },
    "arrival":{
                    "airport": "DEL1",
                    "city": "Delhi"
                },
    "price": 3000,
    "duration": 30,
    "status": "Scheduled"
}

###


GET http://localhost:8000/employeeDashboard/fetchAllFlights
content-type: application/json
