GET http://localhost:3000/login 

###


POST http://localhost:3000/login 
content-type: application/json

{
    "email": "tim@gmail.com",
    "password": "tim"
}

###

POST http://localhost:8000/signup 
content-type: application/json

{
    "name": "ishan",
    "email": "ishan@gmail.com",
    "password": "ishan"
    
}

